services:
  redis:
    image: redis:latest
    container_name: prob_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    name: prob_network
    driver: bridge

volumes:
  redis_data:
    name: prob_data
    driver: local
