services:
  redis:
    image: redis:latest
    container_name: probalistic_trader_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app_network

  postgres:
    image: postgres:14
    container_name: probalistic_trader_postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nautilus_trader
      - POSTGRES_USER=nautilus
      - POSTGRES_PASSWORD=password
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
