services:
  redis:
    image: redis:latest
    container_name: pml-redis
    ports:
      - "6379:6379" # for local redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    name: pml-network
    driver: bridge

volumes:
  redis_data:
    name: pml-data
    driver: local
